### ISSUE TITLE
Ampersands in column data is causing errors.

### ISSUE THREAD

**Issue by Kitsune18** [richardschoen/IbmiXmlserviceStd#2]
I'm extremely new to both IbmiXmlserviecStd and XMLService, we have some data in various columns which contain ampersands (e.g. business names, etc).  How do I turn on the cdata option for XMLService?  I checked in SetUserInfoExt and other places but didn't see any property where I could turn on cdata for the XMLService on the server to return results with cdata.  If there is not a way to turn it on using IbmiXmlserviceStd is there some other way to turn cdata on in XMLService?  If so, how?

Thanks!

**Comment by richardschoen** [comment]
Can you please provide a sample of data you were working with ?  Also were you trying to query or perform an insert/update/delete ?  More info please.

**Comment by Kitsune18** [comment]
Sure!  Right now I'm just starting out so I'm performing only queries at the moment but in a day or two I plan on testing out insert/update/delete. 

How about this example, a company name.
A & A FICTIONAL CO
Data type: Character, length 25, Not nullable, CCSID 37

Names without ampersands appear to be just fine.

We mostly use physical and logical files but some of our new stuff uses SQL tables on the i. 

When executing ExecuteSqlQueryToDataTable the last error reported is "Query failed. Error: An error occurred while parsing EntityName. Line 69, position 30."  

I'm using the 1.0.2 version of IbmiXmlserviceStd.

**Comment by richardschoen** [comment]
I am working on adding the CDATA wrappers. Should be transparent to your code because *cdata will be set to enabled by default, but you will be able to default as well if needed. 1.0.3 will be posted on Nuget and updated here within the next day or two.

**Comment by richardschoen** [comment]
Version 1.0.3 is now on Nuget and source updated here.
