### ISSUE TITLE
How do we execute a stored procedure and receive one or more result sets?

### ISSUE THREAD

**Issue by Kitsune18** [richardschoen/IbmiXmlserviceStd#3]
I had updated to the latest IbmiXmlserviceStd (v1.1.1) via nuget but was unable to figure out how to call a stored procedure that returns one or more result sets.  A little later I figured out that IbmiXmlserviceStd 1.1.1 on nuget isn't the latest and that 1.1.2 here on github actually contains the ability to call stored procedures. I pulled down the source for 1.1.2, compiled it and was able to call a stored procedure that returned a result set. 

I'd like to know if IbmXmlserviceStd is able to read multiple result sets returned by a stored procedure. Do you have any examples of how to read multiple result sets returned from a stored procedure using IbmiXmlserviceStd?

Thank you, in advance! 

p.s. I'm very impressed with IbmiXmlserviceStd.

**Comment by richardschoen** [comment]
Tell me more about your scenario.  

Are you just trying to call an RPG with parms and return a resultset or are you trying to call a pure SQL based stored procedure ?

In 1.1.2, you can simply call a program without declaring as a stored procedure:  EX:  call lib.pgm ('parmvalue1','parmvalue2')   This will return a resultset if your RPG program is SQL enabled and returns a resultset.  I believe you are probably limited to a single resultset with XMLSERVICE.  I have not tried multiple resultset returns. If you need multiple result sets from one call, have your RPG create output files in a temp library that you can then query.

**Comment by richardschoen** [comment]
V1.1.2 posted on Nuget.

**Comment by Kitsune18** [comment]
I was looking to return multiple result sets from a pure SQL based stored procedure.  However since you mentioned that we're probably limited to a single result with XMLSERVICE I'll just create the tables in a temp library as I have done previously. I looked this past weekend to see if there was a way to return multiple result sets from XMLSERVICE but did not find anything. I do not have very much experience with XMLSERVICE but I was hoping I wouldn't have to go the temporary library route. No big deal, I was just trying to get the results back in one go. 

p.s. Thank you very much for updating the Nuget package to v1.1.2
