### ISSUE TITLE
Enhancement request: SSH transport

### ISSUE THREAD

**Issue by ThePrez** [richardschoen/IbmiXmlserviceStd#4]
SSH provides a new, platform-agnistoc way to talk to XMLService. An SSH transport has already been added to the python `itoolkit`: https://github.com/IBM/python-itoolkit/blob/master/src/itoolkit/transport/ssh.py

And v1.x of the Node.js `itoolkit`: https://github.com/IBM/nodejs-itoolkit/blob/v1.0-dev/lib/transports/sshTransport.js

This would require `itoolkit-utils` to be installed to provide the `xmlservice-cli` command that is used. Communication to xmlxervice can be simply done through stdin/stdout access of the `xmlservice-cli` process (see the source code for the other toolkits for examples). 

Thank you for consideration!

**Comment by richardschoen** [comment]
Do you have customers using .Net and XMLSERVICE ?

**Comment by ThePrez** [comment]
I know of several running .NET on Windows and using this toolkit. Not sure about IBM i or Linux.

**Comment by richardschoen** [comment]
Sounds good. I also plan in to checking out the ODBC option as well, but SSH first.

**Comment by ThePrez** [comment]
```
────────────────────░███░
───────────────────░█░░░█░
──────────────────░█░░░░░█░
─────────────────░█░░░░░█░
──────────░░░───░█░░░░░░█░
─────────░███░──░█░░░░░█░
───────░██░░░██░█░░░░░█░
──────░█░░█░░░░██░░░░░█░
────░██░░█░░░░░░█░░░░█░
───░█░░░█░░░░░░░██░░░█░
──░█░░░░█░░░░░░░░█░░░█░
──░█░░░░░█░░░░░░░░█░░░█░
──░█░░█░░░█░░░░░░░░█░░█░
─░█░░░█░░░░██░░░░░░█░░█░
─░█░░░░█░░░░░██░░░█░░░█░
─░█░█░░░█░░░░░░███░░░░█░
░█░░░█░░░██░░░░░█░░░░░█░
░█░░░░█░░░░█████░░░░░█░
░█░░░░░█░░░░░░░█░░░░░█░
░█░█░░░░██░░░░█░░░░░█░
─░█░█░░░░░████░░░░██░
─░█░░█░░░░░░░█░░██░█░
──░█░░██░░░██░░█░░░█░
───░██░░███░░██░█░░█░
────░██░░░███░░░█░░░█░
──────░███░░░░░░█░░░█░
──────░█░░░░░░░░█░░░█░
──────░█░░░░░░░░░░░░█░
──────░█░░░░░░░░░░░░░█░
──────░█░░░░░░░░░░░░░█░
████──░█░████░░░░░░░░█░
█──█──████──████░░░░░█░
█──█──█──█──█──████████
█──█──████──█──█──────█
█──█──█──█────██──██──█
█──████──█──█──█──────█
█─────█──█──█──█──█████
███████──████──█──────█
──────████──██████████
```

**Comment by ThePrez** [comment]
Greetings. Just checking on this one. Is this still on the wish list for the project maintainer(s)?

**Comment by richardschoen** [comment]
It is.

**Comment by Kitsune18** [comment]
ThePrez, I'm not trying to hijack your thread.  I just wanted to add that I too would like to see SSH transport added to this project.  Thanks Richard!

**Comment by richardschoen** [comment]
The Nuget package is available here
https://www.nuget.org/packages/IbmiXmlserviceStdSsh

The source is not currently publicly available for this component, but it works great with .Net and .Net Core.
